swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.1"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Accounts API
      description: Api to get all user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: all accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/AccountsResponse"
            example:
            - id: 0
              title: "Argent Bank Checking (x8349)" 
              amount: 2082.79
              description: "Available Balance"
            - id: 1
              title: "Argent Bank Savings (x6712)"
              amount: 5333.26
              description: "Available Balance"
            - id: 2
              title: "Argent Bank Credit Card (x8349)" 
              amount: 6570.79
              description: "Current Balance"              
        "400":
          description: Accounts not found
        "500":
          description: Internal Server Error
  /user/accounts/{account_id}/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API to get all transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: account_id
          description: account id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: All transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transactions"
            example:
            - id: 0
              date: "2024-03-05T07:47:40.423Z"
              description: "Payment at Starbucks"
              amount: 50
              balance: 2032.79
            - id: 1
              date: "2024-03-05T07:47:40.423Z"
              description: "Payment at Starbucks"
              amount: 25
              balance: 2082.79
            - id: 2
              date: "2024-03-04T11:05:42.000Z"
              description: "Movie ticket purchase"
              amount: 15.00
              balance: 2210.29
        "400":
          description: Invalid Field
        "500":
          description: Internal Server Error
  /user/account/{account_id}/transaction/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API to get a detail of a single transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transaction_id
          description: Transaction ID
          required: true
          type: integer
        - in: path
          name: account_id
          description: Account ID
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: A single transaction retrieved successully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Field
        "500":
          description: Internal Server Error
  /user/accounts/{account_id}/transactions/{transaction_id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for updating a category of transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          description: transaction ID
          name: transaction_id
          required: true
          type: integer
        - in: path
          description: account ID
          name: account_id
          required: true
          type: integer
        - in: body
          name: body
          description: Update account transaction attributes
          required: true
          schema:
            $ref: "#/definitions/TransactionsEdit"
      produces:
        - application/json
      responses:
        "200":
          description: updated transaction successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionsEdit:
    properties:
      category:
        type: string
        description: transaction category.
        example : Grocery shopping
      note:
        type: string
        description: transaction note.
        example : Lorem ipsum
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transactions:
        type: object
        properties:
          id:
            type: integer
            description: transaction id.
          date:
            type: string
            format: date-time
            description: transaction date.
          description:
            type: string
            description: transaction description.
          amount:
            type: number
            description: transaction amount.
          balance:
            type: number
            description: transaction balance.
  AccountsResponse:
    type: object
    items:
      type: object
    properties:
      id:
        type: integer
        description: account id
      title:
        type: string
        description: account title
      amount:
        type: number
        description: account amount
      description:
        type: string
        description: account description
  TransactionsResponse:
    type: object
    properties:
      id:
        type: integer
        description: The unique identifier of the transaction.
      date:
        type: string
        format: date-time
        description: transaction date
      description:
        type: string
        description: transaction description.
        example: Payment at Starbucks
      amount:
        type: number
        description: transaction amount.
        example: 50.00
      balance:
        type: number
        description: transaction balance.
        example: 2032.79
      transactionType:
        type: string
        description: transaction type.
        example: Electronic
      category:
        type: string
        description: transaction category.
        example: Grocery shopping
      note:
        type: string
        description: transaction note.
        example: Lorem ipsum
  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
        description: The unique identifier of the transaction.
      date:
        type: string
        format: date-time
        description: transaction date
      description:
        type: string
        description: transaction description.
        example: Payment at Starbucks
      amount:
        type: number
        description: transaction amount.
        example: 50.00
      balance:
        type: number
        description: transaction balance.
        example: 2032.79
      transactionType:
        type: string
        description: transaction type.
        example: Electronic
      category:
        type: string
        description: transaction category.
        example: Food
      note:
        type: string
        description: transaction note.
        example: Lorem ipsum